import Head from 'next/head'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <div >
      <Head>
        <title>G-Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link url='' />
      </Head>
      {/* <h1>Yooooo</h1> */}
      <Sidebar />
    </div>
  )
}
